name: Archive the TPs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  archive:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tp: [1]
    steps:

    # Setup
    - name: "[Setup] checkout"
      uses: actions/checkout@v2
    - name: "[Setup] install Pandoc"
      run: sudo apt install -y pandoc texlive texlive-latex-extra
    - name: "[TP${{ matrix.tp }}] prepare archive"
      working-directory: tp${{ matrix.tp }}
      run: |
        make clean
        make rapport.pdf
    - name: "[TP${{ matrix.tp }}] upload archive"
      uses: actions/upload-artifact@v2.3.1
      with:
        name: DECORSAIRE-GELEZ-ONGHENA-TP${{ matrix.tp }}
        path: tp${{ matrix.tp }}/*
  
